build:
  binary: changelogger
  main: main.go
  ldflags:
    - >
      -s -w 
      -X github.com/MarkusFreitag/changelogger/cmd.BuildVersion={{.Version}}
      -X github.com/MarkusFreitag/changelogger/cmd.BuildDate={{.Date}}
  goos:
    - linux
  goarch:
    - amd64
  env:
    - CGO_ENABLED=0

archives:
  - name_template: "{{.Binary}}_{{.Os}}_{{.Arch}}"

release:
  draft: true

snapshot:
  name_template: "{{.Tag}}"

checksum:
  name_template: "changelogger_checksums.txt"

nfpms:
  - vendor: Changelogger
    homepage: https://github.com/MarkusFreitag/changelogger
    maintainer: Markus Freitag <fmarkus@mailbox.org> 
    description: Create and update changelog files interactively
    license: MIT
    formats:
      - deb
      - rpm
    file_name_template: "{{.ProjectName}}_{{.Os}}_{{.Arch}}"
