language: go

go:
  - 1.13.x
  - 1.14.x

addons:
  apt:
    packages:
      - rpm

env:
  - GO111MODULE=on

script:
  - curl -s https://taskfile.org/install.sh | sh
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin
  - ./bin/task ci

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL http://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
